export const PARTNER_FIRM = {
  name: "Partner Immigration Law",
  attorney: "Jeremy \"Yirmi\" Knight, Esq.",
  barNumber: "1009132",
  barState: "FL",
  firm: "Partner Immigration Law, PLLC",
  phone: "(954) 777-6678",
  email: "Yirmi@LadyLibertyLawyers.com",
  address: "Fort Lauderdale, Broward County, FL",
  website: "https://ladylibertylawyers.com",
  specialties: ["Family-Based Immigration", "Marriage Green Cards", "Adjustment of Status", "Naturalization", "Commercial Litigation"],
  languages: ["English", "Spanish"],
  bio: "Highly-regarded and award-winning attorney with extensive experience in immigration and international law. Graduate of Florida International University College of Law. Known for strong client relationships and a track record of success. Florida Bar member, Trial Lawyers Section and Business Law Section.",
  consultationFee: 0,
};
