/**
 * I-485 Form Definition
 * Application to Register Permanent Residence or Adjust Status
 * 
 * This form is filed to apply for adjustment to permanent resident status
 * or to have your immigrant visa immediately available for issuance.
 */

import type { FormDefinition, FormField, FormSection } from "./i-130";

const part1Fields: FormField[] = [
  {
    id: "i485_name_first",
    label: "First Name",
    type: "text",
    required: true,
    section: "part1",
    helpText: "Your legal first name",
    validationRules: [{ type: "required", message: "First name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_name_middle",
    label: "Middle Name(s)",
    type: "text",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_name_last",
    label: "Last Name / Family Name",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Last name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_date_of_birth",
    label: "Date of Birth",
    type: "date",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Date of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_country_of_birth",
    label: "Country of Birth",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Country of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_country_of_citizenship",
    label: "Country of Citizenship",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Country of citizenship is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_gender",
    label: "Gender",
    type: "select",
    required: true,
    section: "part1",
    options: [
      { value: "M", label: "Male" },
      { value: "F", label: "Female" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_marital_status",
    label: "Marital Status",
    type: "select",
    required: true,
    section: "part1",
    options: [
      { value: "single", label: "Single" },
      { value: "married", label: "Married" },
      { value: "divorced", label: "Divorced" },
      { value: "widowed", label: "Widowed" },
      { value: "separated", label: "Legally Separated" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_height",
    label: "Height",
    type: "text",
    required: false,
    section: "part1",
    placeholder: "e.g., 5'10\"",
    rfeRisk: "low",
  },
  {
    id: "i485_eye_color",
    label: "Eye Color",
    type: "select",
    required: false,
    section: "part1",
    options: [
      { value: "black", label: "Black" },
      { value: "blue", label: "Blue" },
      { value: "brown", label: "Brown" },
      { value: "green", label: "Green" },
      { value: "hazel", label: "Hazel" },
      { value: "maroon", label: "Maroon" },
      { value: "pink", label: "Pink" },
      { value: "unknown", label: "Unknown" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_hair_color",
    label: "Hair Color",
    type: "select",
    required: false,
    section: "part1",
    options: [
      { value: "bald", label: "Bald" },
      { value: "black", label: "Black" },
      { value: "blonde", label: "Blonde" },
      { value: "brown", label: "Brown" },
      { value: "gray", label: "Gray" },
      { value: "red", label: "Red" },
      { value: "sandy", label: "Sandy" },
      { value: "white", label: "White" },
      { value: "unknown", label: "Unknown" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_distinguishing_marks",
    label: "Distinguishing Marks (scars, birthmarks, tattoos, etc.)",
    type: "text",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_ssn",
    label: "Social Security Number",
    type: "ssn",
    required: false,
    section: "part1",
    helpText: "If you have received a Social Security Number",
    rfeRisk: "low",
  },
  {
    id: "i485_a_number",
    label: "USCIS Number",
    type: "text",
    required: false,
    section: "part1",
    helpText: "Your A-Number or I-94 number if available",
    rfeRisk: "low",
  },
  {
    id: "i485_i94_number",
    label: "I-94 Admission Number",
    type: "text",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_current_address_street",
    label: "Current Street Address",
    type: "address",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Street address is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_current_address_city",
    label: "Current City / Town",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "City is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_current_address_state",
    label: "Current State / Province",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "State is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_current_address_zip",
    label: "Current ZIP / Postal Code",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "ZIP code is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_current_address_country",
    label: "Current Country",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Country is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_phone",
    label: "Phone Number",
    type: "phone",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Phone number is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_email",
    label: "Email Address",
    type: "text",
    required: true,
    section: "part1",
    validationRules: [{ type: "required", message: "Email is required" }],
    rfeRisk: "low",
  },
  {
    id: "i485_prior_address_3_years",
    label: "Have you lived at your current address for less than 3 years?",
    type: "checkbox",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_prior_address",
    label: "Previous Address(es) for Last 5 Years",
    type: "textarea",
    required: false,
    section: "part1",
    helpText: "List all addresses where you have lived in the past 5 years",
    rfeRisk: "low",
  },
  {
    id: "i485_emergency_contact",
    label: "Emergency Contact Name",
    type: "text",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_emergency_contact_phone",
    label: "Emergency Contact Phone",
    type: "phone",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
  {
    id: "i485_emergency_contact_relationship",
    label: "Emergency Contact Relationship",
    type: "text",
    required: false,
    section: "part1",
    rfeRisk: "low",
  },
];

const part2Fields: FormField[] = [
  {
    id: "i485_application_type",
    label: "Application Type",
    type: "select",
    required: true,
    section: "part2",
    helpText: "Indicate why you are filing this application",
    options: [
      { value: "immediate_relative", label: "Immediate Relative of U.S. Citizen" },
      { value: "employment", label: "Employment-Based Immigrant" },
      { value: "family_preference", label: "Family Preference Immigrant" },
      { value: "diversity", label: "Diversity Immigrant" },
      { value: "humanitarian", label: "Humanitarian" },
      { value: "special_immigrant", label: "Special Immigrant" },
      { value: "other", label: "Other" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_immediate_relative_type",
    label: "If Immediate Relative, Specify Relationship",
    type: "select",
    required: false,
    section: "part2",
    options: [
      { value: "spouse", label: "Spouse of U.S. Citizen" },
      { value: "parent", label: "Parent of U.S. Citizen" },
      { value: "orphan", label: "Orphan to be Adopted by U.S. Citizen" },
      { value: "widow", label: "Widow(er) of U.S. Citizen" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_employment_based_preference",
    label: "Employment-Based Preference Category",
    type: "select",
    required: false,
    section: "part2",
    options: [
      { value: "eb1a", label: "EB-1A: Priority Workers" },
      { value: "eb1b", label: "EB-1B: Outstanding Researchers" },
      { value: "eb1c", label: "EB-1C: Managers/Executives" },
      { value: "eb2", label: "EB-2: Professionals with Advanced Degrees" },
      { value: "eb3", label: "EB-3: Skilled Workers" },
      { value: "eb4", label: "EB-4: Special Immigrants" },
      { value: "eb5", label: "EB-5: Investors" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_visa_petition_number",
    label: "Visa Petition / I-140 Receipt Number",
    type: "text",
    required: false,
    section: "part2",
    rfeRisk: "low",
  },
  {
    id: "i485_priority_date",
    label: "Priority Date",
    type: "date",
    required: false,
    section: "part2",
    helpText: "The priority date from your immigrant petition",
    rfeRisk: "low",
  },
  {
    id: "i485_consular_notification",
    label: "Are you applying for adjustment of status or consular processing?",
    type: "select",
    required: true,
    section: "part2",
    options: [
      { value: "adjustment", label: "Adjustment of Status (AOS)" },
      { value: "consular", label: "Consular Processing" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i485_petitioner_us_citizen",
    label: "Is your petitioner a U.S. citizen?",
    type: "checkbox",
    required: false,
    section: "part2",
    rfeRisk: "low",
  },
  {
    id: "i485_filing_fee_waiver",
    label: "Are you requesting a fee waiver?",
    type: "checkbox",
    required: false,
    section: "part2",
    rfeRisk: "low",
  },
  {
    id: "i485_biometric_reuse",
    label: "May USCIS reuse your biometrics from a recent application?",
    type: "checkbox",
    required: false,
    section: "part2",
    rfeRisk: "low",
  },
  {
    id: "i485_biometric_receipt",
    label: "Receipt Number of Previous Biometric Application",
    type: "text",
    required: false,
    section: "part2",
    rfeRisk: "low",
  },
];

const part3Fields: FormField[] = [
  {
    id: "i485_parent_names",
    label: "Father's Name",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_mother_name",
    label: "Mother's Name",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_mother_citizenship",
    label: "Mother's Country of Birth",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_father_citizenship",
    label: "Father's Country of Birth",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_current_nonimmigrant_status",
    label: "What is your current nonimmigrant status in the U.S.?",
    type: "select",
    required: false,
    section: "part3",
    options: [
      { value: "b1b2", label: "B-1/B-2 (Visitor)" },
      { value: "f1", label: "F-1 (Student)" },
      { value: "h1b", label: "H-1B (Worker)" },
      { value: "l1", label: "L-1 (Intracompany Transferee)" },
      { value: "o1", label: "O-1 (Extraordinary Ability)" },
      { value: "e2", label: "E-2 (Treaty Investor)" },
      { value: "j1", label: "J-1 (Exchange Visitor)" },
      { value: "none", label: "No status (Undocumented)" },
    ],
    rfeRisk: "medium",
  },
  {
    id: "i485_date_arrived_us",
    label: "Date of Arrival in the United States",
    type: "date",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_i94_expiration",
    label: "Expiration Date of Your Authorized Stay",
    type: "date",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_entered_without_inspection",
    label: "Did you enter the U.S. with an inspection by an immigration official?",
    type: "checkbox",
    required: false,
    section: "part3",
    rfeRisk: "high",
  },
  {
    id: "i485_crossing_location",
    label: "Port of Entry / Crossing Location",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_employment_authorization",
    label: "Do you have employment authorization in the U.S.?",
    type: "checkbox",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_employment_authorization_number",
    label: "Employment Authorization Document Number",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_advance_parole",
    label: "Do you have Advance Parole (AP) authorization?",
    type: "checkbox",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_advance_parole_number",
    label: "Advance Parole Authorization Number",
    type: "text",
    required: false,
    section: "part3",
    rfeRisk: "low",
  },
  {
    id: "i485_asylum_pending",
    label: "Do you have a pending asylum application?",
    type: "checkbox",
    required: false,
    section: "part3",
    rfeRisk: "medium",
  },
  {
    id: "i485_asylum_details",
    label: "Asylum Application Details",
    type: "textarea",
    required: false,
    section: "part3",
    rfeRisk: "medium",
  },
];

const part4Fields: FormField[] = [
  {
    id: "i485_special_needs_accommodation",
    label: "Do you require an interpreter for the interview?",
    type: "checkbox",
    required: false,
    section: "part4",
    rfeRisk: "low",
  },
  {
    id: "i485_interpreter_language",
    label: "Interpreter Language",
    type: "text",
    required: false,
    section: "part4",
    rfeRisk: "low",
  },
  {
    id: "i485_disability_accommodation",
    label: "Do you have a disability requiring reasonable accommodations?",
    type: "checkbox",
    required: false,
    section: "part4",
    rfeRisk: "low",
  },
  {
    id: "i485_disability_description",
    label: "Description of Disability / Accommodation Needed",
    type: "textarea",
    required: false,
    section: "part4",
    rfeRisk: "low",
  },
  {
    id: "i485_medical_examination_completed",
    label: "Have you completed the required medical examination (Form I-693)?",
    type: "checkbox",
    required: false,
    section: "part4",
    rfeRisk: "low",
  },
];

// Background information - yes/no with explanation fields
const part5Fields: FormField[] = [
  {
    id: "i485_criminal_conviction",
    label: "Have you ever been convicted of a crime of moral turpitude or any other crime?",
    type: "checkbox",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_criminal_conviction_explanation",
    label: "If yes, provide details",
    type: "textarea",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_drug_offense",
    label: "Have you ever been arrested for, convicted of, or admitted committing a drug-related offense?",
    type: "checkbox",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_drug_offense_explanation",
    label: "If yes, provide details",
    type: "textarea",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_immigration_fraud",
    label: "Have you ever willfully misrepresented a material fact in seeking an immigration benefit?",
    type: "checkbox",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_immigration_fraud_explanation",
    label: "If yes, provide details",
    type: "textarea",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_deportation",
    label: "Have you ever been deported, removed, or ordered to leave the U.S.?",
    type: "checkbox",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_deportation_explanation",
    label: "If yes, provide details",
    type: "textarea",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_security_risk",
    label: "Do you believe you may be a security or public safety risk?",
    type: "checkbox",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
  {
    id: "i485_security_risk_explanation",
    label: "If yes, provide details",
    type: "textarea",
    required: false,
    section: "part5",
    rfeRisk: "high",
  },
];

const part6Fields: FormField[] = [
  {
    id: "i485_work_history_summary",
    label: "Describe Your Employment History for the Past 5 Years",
    type: "textarea",
    required: false,
    section: "part6",
    helpText: "List employers, job titles, dates, and locations",
    rfeRisk: "low",
  },
  {
    id: "i485_education_history",
    label: "Describe Your Education and Relevant Training",
    type: "textarea",
    required: false,
    section: "part6",
    helpText: "List schools, degrees, certifications, and dates attended",
    rfeRisk: "low",
  },
];

const part7Fields: FormField[] = [
  {
    id: "i485_family_member_us",
    label: "Do you have any family members who are U.S. citizens or permanent residents?",
    type: "checkbox",
    required: false,
    section: "part7",
    rfeRisk: "low",
  },
  {
    id: "i485_family_member_details",
    label: "Family Members in the U.S.",
    type: "textarea",
    required: false,
    section: "part7",
    helpText: "Provide names, relationships, and status",
    rfeRisk: "low",
  },
];

export const i485FormDefinition: FormDefinition = {
  id: "i-485",
  formNumber: "I-485",
  title: "Application to Register Permanent Residence or Adjust Status",
  description:
    "This form is filed to apply for adjustment to permanent resident status in the United States or to have your immigrant visa immediately available for issuance.",
  effectiveDate: "01/01/2023",
  sections: [
    {
      id: "part1",
      title: "Part 1: Your Information",
      description: "Personal details and contact information",
      fields: part1Fields,
    },
    {
      id: "part2",
      title: "Part 2: Application Type and Eligibility",
      description: "Information about your immigration classification and eligibility",
      fields: part2Fields,
    },
    {
      id: "part3",
      title: "Part 3: Processing Information",
      description: "Immigration status and arrival information",
      fields: part3Fields,
    },
    {
      id: "part4",
      title: "Part 4: Accommodation for Disabilities",
      description: "Special needs and accessibility information",
      fields: part4Fields,
    },
    {
      id: "part5",
      title: "Part 5: Background Questions",
      description: "Criminal history and immigration violations",
      fields: part5Fields,
    },
    {
      id: "part6",
      title: "Part 6: Employment and Education History",
      description: "Work and education background",
      fields: part6Fields,
    },
    {
      id: "part7",
      title: "Part 7: Family Information",
      description: "Family relationships and status",
      fields: part7Fields,
    },
  ],
  fieldCount: part1Fields.length + part2Fields.length + part3Fields.length + part4Fields.length + part5Fields.length + part6Fields.length + part7Fields.length,
  estimatedTime: 60,
};

export default i485FormDefinition;
