/**
 * I-765 Form Definition
 * Application for Employment Authorization
 * 
 * This form is used to request employment authorization for eligible categories
 * such as asylees, refugees, H-4 dependent spouses, F-1 students, and others.
 */

import type { FormDefinition, FormField, FormSection } from "./i-130";

const applicantInfoFields: FormField[] = [
  {
    id: "i765_name_first",
    label: "First Name",
    type: "text",
    required: true,
    section: "applicant_info",
    helpText: "Your legal first name",
    validationRules: [{ type: "required", message: "First name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_name_middle",
    label: "Middle Name(s)",
    type: "text",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_name_last",
    label: "Last Name / Family Name",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Last name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_date_of_birth",
    label: "Date of Birth",
    type: "date",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Date of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_country_of_citizenship",
    label: "Country of Citizenship",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Country of citizenship is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_country_of_birth",
    label: "Country of Birth",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Country of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_gender",
    label: "Gender",
    type: "select",
    required: true,
    section: "applicant_info",
    options: [
      { value: "M", label: "Male" },
      { value: "F", label: "Female" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i765_marital_status",
    label: "Marital Status",
    type: "select",
    required: true,
    section: "applicant_info",
    options: [
      { value: "single", label: "Single" },
      { value: "married", label: "Married" },
      { value: "divorced", label: "Divorced" },
      { value: "widowed", label: "Widowed" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i765_ssn",
    label: "Social Security Number",
    type: "ssn",
    required: false,
    section: "applicant_info",
    helpText: "If you have been assigned a Social Security Number",
    rfeRisk: "low",
  },
  {
    id: "i765_alien_number",
    label: "USCIS Number (A-Number)",
    type: "text",
    required: false,
    section: "applicant_info",
    helpText: "Your A-Number if you have received one",
    rfeRisk: "low",
  },
  {
    id: "i765_passport_number",
    label: "Passport Number",
    type: "text",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_passport_country",
    label: "Country that Issued Passport",
    type: "text",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_passport_expiration",
    label: "Passport Expiration Date",
    type: "date",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_i94_number",
    label: "I-94 Admission Number",
    type: "text",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_current_address",
    label: "Current Mailing Address",
    type: "address",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Mailing address is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_city",
    label: "City / Town",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "City is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_state",
    label: "State / Province",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "State is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_zip",
    label: "ZIP / Postal Code",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "ZIP code is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_country",
    label: "Country",
    type: "text",
    required: true,
    section: "applicant_info",
    validationRules: [{ type: "required", message: "Country is required" }],
    rfeRisk: "low",
  },
  {
    id: "i765_phone",
    label: "Telephone Number",
    type: "phone",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
  {
    id: "i765_email",
    label: "Email Address",
    type: "text",
    required: false,
    section: "applicant_info",
    rfeRisk: "low",
  },
];

const eligibilityFields: FormField[] = [
  {
    id: "i765_eligibility_category",
    label: "Eligibility Category",
    type: "select",
    required: true,
    section: "eligibility",
    helpText: "Select the category under which you are requesting employment authorization",
    options: [
      { value: "a04", label: "(a)(4) - I-130 Pending" },
      { value: "c03", label: "(c)(3) - Asylee" },
      { value: "a05", label: "(a)(5) - Refugee" },
      { value: "c03c", label: "(c)(3) - TPS" },
      { value: "a10", label: "(a)(10) - Paroled Refugee" },
      { value: "h04", label: "(h)(4) - H-4 Dependent" },
      { value: "f01", label: "(f)(1) - F-1 Student" },
      { value: "l02", label: "(l)(2) - L-2 Dependent" },
      { value: "j02", label: "(j)(2) - J-2 Dependent" },
      { value: "c16", label: "(c)(16) - Provisional Waiver" },
      { value: "c26", label: "(c)(26) - DACA" },
      { value: "other", label: "Other" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i765_category_details",
    label: "Provide Details About Your Eligibility",
    type: "textarea",
    required: true,
    section: "eligibility",
    helpText: "Explain your eligibility category and provide relevant case details",
    validationRules: [{ type: "required", message: "Category details are required" }],
    rfeRisk: "medium",
  },
  {
    id: "i765_asylum_number",
    label: "Asylum Case Number (if applicable)",
    type: "text",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
  {
    id: "i765_i130_number",
    label: "I-130 Petition Number (if applicable)",
    type: "text",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
  {
    id: "i765_i485_pending",
    label: "Is your I-485 application pending?",
    type: "checkbox",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
  {
    id: "i765_days_pending",
    label: "How many days has your I-485 been pending?",
    type: "text",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
];

const employmentFields: FormField[] = [
  {
    id: "i765_current_employment",
    label: "Are you currently employed?",
    type: "checkbox",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_employer_name",
    label: "Current Employer Name",
    type: "text",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_job_title",
    label: "Job Title",
    type: "text",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_employment_start_date",
    label: "Employment Start Date",
    type: "date",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_employer_phone",
    label: "Employer Phone Number",
    type: "phone",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_job_duties",
    label: "Description of Job Duties",
    type: "textarea",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_wage_rate",
    label: "Wage Rate / Salary",
    type: "text",
    required: false,
    section: "employment",
    rfeRisk: "low",
  },
  {
    id: "i765_work_authorization_end_date",
    label: "Requested Work Authorization End Date",
    type: "date",
    required: false,
    section: "employment",
    helpText: "Desired expiration date for your employment authorization",
    rfeRisk: "low",
  },
  {
    id: "i765_specific_employment",
    label: "Is this for a specific employer or for any employment?",
    type: "select",
    required: false,
    section: "employment",
    options: [
      { value: "specific", label: "Specific Employer" },
      { value: "any", label: "Any Employment" },
    ],
    rfeRisk: "low",
  },
];

const representsFields: FormField[] = [
  {
    id: "i765_attorney_representative",
    label: "Is an attorney or representative assisting you?",
    type: "checkbox",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
  {
    id: "i765_representative_name",
    label: "Representative Name",
    type: "text",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
  {
    id: "i765_representative_phone",
    label: "Representative Phone",
    type: "phone",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
  {
    id: "i765_representative_fax",
    label: "Representative Fax",
    type: "text",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
  {
    id: "i765_bar_number",
    label: "Bar Number",
    type: "text",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
  {
    id: "i765_state_bar",
    label: "State Bar",
    type: "text",
    required: false,
    section: "representation",
    rfeRisk: "low",
  },
];

const declarationFields: FormField[] = [
  {
    id: "i765_declaration_true",
    label: "I certify that the above information is true and correct",
    type: "checkbox",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "You must certify the information is true and correct" }],
    rfeRisk: "low",
  },
  {
    id: "i765_signature_date",
    label: "Date of Signature",
    type: "date",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "Signature date is required" }],
    rfeRisk: "low",
  },
];

export const i765FormDefinition: FormDefinition = {
  id: "i-765",
  formNumber: "I-765",
  title: "Application for Employment Authorization",
  description:
    "This form is filed to request employment authorization for eligible categories such as asylees, refugees, H-4 dependent spouses, F-1 students, and pending I-485 applicants. Employment authorization allows you to work legally in the United States.",
  effectiveDate: "06/01/2023",
  sections: [
    {
      id: "applicant_info",
      title: "Applicant Information",
      description: "Personal and biographical information",
      fields: applicantInfoFields,
    },
    {
      id: "eligibility",
      title: "Eligibility Category",
      description: "Information about your eligibility for employment authorization",
      fields: eligibilityFields,
    },
    {
      id: "employment",
      title: "Employment Information",
      description: "Details about your employment or intended employment",
      fields: employmentFields,
    },
    {
      id: "representation",
      title: "Representative Information",
      description: "Attorney or representative information if applicable",
      fields: representsFields,
    },
    {
      id: "declaration",
      title: "Declaration and Signature",
      description: "Certification and signature",
      fields: declarationFields,
    },
  ],
  fieldCount: applicantInfoFields.length + eligibilityFields.length + employmentFields.length + representsFields.length + declarationFields.length,
  estimatedTime: 30,
};

export default i765FormDefinition;
