/**
 * I-864 Form Definition
 * Affidavit of Support
 * 
 * This form is filed by a sponsor to demonstrate they have the financial
 * ability to support the intending immigrant and that the immigrant will
 * not become a public charge.
 */

import type { FormDefinition, FormField, FormSection } from "./i-130";

const sponsorInfoFields: FormField[] = [
  {
    id: "i864_sponsor_name_first",
    label: "First Name",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "First name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_name_last",
    label: "Last Name",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "Last name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_date_of_birth",
    label: "Date of Birth",
    type: "date",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "Date of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_citizenship",
    label: "Citizenship Status",
    type: "select",
    required: true,
    section: "sponsor_info",
    options: [
      { value: "citizen", label: "U.S. Citizen" },
      { value: "permanent", label: "Permanent Resident" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_ssn",
    label: "Social Security Number",
    type: "ssn",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "SSN is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_alien_number",
    label: "USCIS Number (if applicable)",
    type: "text",
    required: false,
    section: "sponsor_info",
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_current_address",
    label: "Current Mailing Address",
    type: "address",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "Address is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_city",
    label: "City / Town",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "City is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_state",
    label: "State",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "State is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_zip",
    label: "ZIP Code",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "ZIP code is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_phone",
    label: "Phone Number",
    type: "phone",
    required: false,
    section: "sponsor_info",
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_email",
    label: "Email Address",
    type: "text",
    required: false,
    section: "sponsor_info",
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_occupation",
    label: "Current Occupation",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "Occupation is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_employer",
    label: "Current Employer Name",
    type: "text",
    required: true,
    section: "sponsor_info",
    validationRules: [{ type: "required", message: "Employer name is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_relationship",
    label: "Relationship to Intending Immigrant",
    type: "select",
    required: true,
    section: "sponsor_info",
    options: [
      { value: "spouse", label: "Spouse" },
      { value: "parent", label: "Parent" },
      { value: "child", label: "Child" },
      { value: "sibling", label: "Sibling" },
      { value: "relative", label: "Other Relative" },
      { value: "non_relative", label: "Non-Relative" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i864_sponsor_has_dependents",
    label: "Do you have any dependents?",
    type: "checkbox",
    required: false,
    section: "sponsor_info",
    rfeRisk: "low",
  },
];

const householdFields: FormField[] = [
  {
    id: "i864_household_size",
    label: "Total Number of People in Your Household",
    type: "text",
    required: true,
    section: "household",
    placeholder: "Enter number",
    validationRules: [{ type: "required", message: "Household size is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_household_list",
    label: "List All Household Members (Name, Relationship, Age)",
    type: "textarea",
    required: true,
    section: "household",
    helpText: "Include yourself and all dependents",
    validationRules: [{ type: "required", message: "Household members must be listed" }],
    rfeRisk: "low",
  },
  {
    id: "i864_dependents_count",
    label: "Number of Dependents",
    type: "text",
    required: false,
    section: "household",
    placeholder: "Enter number",
    rfeRisk: "low",
  },
  {
    id: "i864_immigrants_being_sponsored",
    label: "Number of Intending Immigrants You Are Sponsoring",
    type: "text",
    required: true,
    section: "household",
    placeholder: "Enter number",
    validationRules: [{ type: "required", message: "Number of immigrants is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_other_sponsored_immigrants",
    label: "Have you sponsored other immigrants previously?",
    type: "checkbox",
    required: false,
    section: "household",
    rfeRisk: "medium",
  },
  {
    id: "i864_other_sponsored_details",
    label: "Details of Other Immigrants You Have Sponsored",
    type: "textarea",
    required: false,
    section: "household",
    rfeRisk: "medium",
  },
];

const incomeFields: FormField[] = [
  {
    id: "i864_annual_income",
    label: "Your Annual Income (Gross)",
    type: "text",
    required: true,
    section: "income",
    placeholder: "Enter amount in USD",
    validationRules: [{ type: "required", message: "Annual income is required" }],
    rfeRisk: "low",
  },
  {
    id: "i864_income_source",
    label: "Source of Income",
    type: "select",
    required: true,
    section: "income",
    options: [
      { value: "employment", label: "Employment" },
      { value: "business", label: "Self-Employment" },
      { value: "social_security", label: "Social Security" },
      { value: "pension", label: "Pension / Retirement" },
      { value: "investment", label: "Investment Income" },
      { value: "rental", label: "Rental Income" },
      { value: "other", label: "Other" },
    ],
    rfeRisk: "low",
  },
  {
    id: "i864_employment_months",
    label: "How long have you been employed (in months)?",
    type: "text",
    required: false,
    section: "income",
    placeholder: "Enter number",
    rfeRisk: "low",
  },
  {
    id: "i864_spouse_income",
    label: "Your Spouse's Annual Income (if applicable)",
    type: "text",
    required: false,
    section: "income",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_other_household_income",
    label: "Other Household Members' Annual Income",
    type: "text",
    required: false,
    section: "income",
    placeholder: "Enter total amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_total_household_income",
    label: "Total Annual Household Income",
    type: "text",
    required: true,
    section: "income",
    placeholder: "Enter amount in USD",
    validationRules: [{ type: "required", message: "Total household income is required" }],
    rfeRisk: "low",
  },
];

const assetsFields: FormField[] = [
  {
    id: "i864_has_assets",
    label: "Do you have assets to support the immigrant?",
    type: "checkbox",
    required: false,
    section: "assets",
    rfeRisk: "low",
  },
  {
    id: "i864_real_estate_value",
    label: "Real Estate Value (excluding primary residence)",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_savings_accounts",
    label: "Savings and Checking Accounts",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_stocks_bonds",
    label: "Stocks, Bonds, and Other Securities",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_retirement_accounts",
    label: "Retirement Accounts (401k, IRA, etc.)",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_business_assets",
    label: "Business Assets",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_vehicles",
    label: "Vehicles (excluding primary vehicle)",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_total_assets",
    label: "Total Assets",
    type: "text",
    required: false,
    section: "assets",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
];

const taxFields: FormField[] = [
  {
    id: "i864_filed_tax_return",
    label: "Have you filed a U.S. tax return for the last 3 years?",
    type: "checkbox",
    required: false,
    section: "taxes",
    rfeRisk: "low",
  },
  {
    id: "i864_tax_return_years",
    label: "Tax Return Years Filed",
    type: "text",
    required: false,
    section: "taxes",
    helpText: "e.g., 2021, 2022, 2023",
    rfeRisk: "low",
  },
  {
    id: "i864_agi_last_year",
    label: "Adjusted Gross Income (AGI) - Last Year",
    type: "text",
    required: false,
    section: "taxes",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_agi_two_years",
    label: "Adjusted Gross Income (AGI) - 2 Years Ago",
    type: "text",
    required: false,
    section: "taxes",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_agi_three_years",
    label: "Adjusted Gross Income (AGI) - 3 Years Ago",
    type: "text",
    required: false,
    section: "taxes",
    placeholder: "Enter amount in USD",
    rfeRisk: "low",
  },
  {
    id: "i864_will_submit_tax_returns",
    label: "Will submit copy of last 3 tax returns",
    type: "checkbox",
    required: true,
    section: "taxes",
    validationRules: [{ type: "required", message: "Must agree to submit tax returns" }],
    rfeRisk: "low",
  },
];

const declarationFields: FormField[] = [
  {
    id: "i864_declaration_true",
    label: "I certify under penalty of perjury that the foregoing information is true and correct",
    type: "checkbox",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "You must certify the information is true and correct" }],
    rfeRisk: "low",
  },
  {
    id: "i864_signature_date",
    label: "Date of Signature",
    type: "date",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "Signature date is required" }],
    rfeRisk: "low",
  },
];

export const i864FormDefinition: FormDefinition = {
  id: "i-864",
  formNumber: "I-864",
  title: "Affidavit of Support",
  description:
    "This form is filed by a sponsor to demonstrate that they have sufficient income and assets to support an intending immigrant and prevent them from becoming a public charge. The sponsor is financially responsible for the immigrant for 10 years or until the immigrant becomes a U.S. citizen.",
  effectiveDate: "04/01/2023",
  sections: [
    {
      id: "sponsor_info",
      title: "Sponsor Information",
      description: "Personal information about the sponsor",
      fields: sponsorInfoFields,
    },
    {
      id: "household",
      title: "Household Information",
      description: "Household size and members being sponsored",
      fields: householdFields,
    },
    {
      id: "income",
      title: "Annual Income",
      description: "Income information for the household",
      fields: incomeFields,
    },
    {
      id: "assets",
      title: "Assets",
      description: "Financial assets available to support the immigrant",
      fields: assetsFields,
    },
    {
      id: "taxes",
      title: "Tax Return Information",
      description: "Tax filing history and AGI information",
      fields: taxFields,
    },
    {
      id: "declaration",
      title: "Declaration and Signature",
      description: "Certification and signature",
      fields: declarationFields,
    },
  ],
  fieldCount: sponsorInfoFields.length + householdFields.length + incomeFields.length + assetsFields.length + taxFields.length + declarationFields.length,
  estimatedTime: 40,
};

export default i864FormDefinition;
