/**
 * N-400 Form Definition
 * Application for Naturalization
 * 
 * This form is filed to apply for U.S. citizenship through naturalization.
 * You must be a permanent resident and meet various eligibility requirements.
 */

import type { FormDefinition, FormField, FormSection } from "./i-130";

const eligibilityFields: FormField[] = [
  {
    id: "n400_citizenship_years",
    label: "How long have you been a permanent resident?",
    type: "select",
    required: true,
    section: "eligibility",
    options: [
      { value: "3years", label: "3 years or more" },
      { value: "5years", label: "5 years or more" },
      { value: "less3", label: "Less than 3 years" },
    ],
    rfeRisk: "low",
  },
  {
    id: "n400_permanent_resident_date",
    label: "Date You Became a Permanent Resident",
    type: "date",
    required: true,
    section: "eligibility",
    validationRules: [{ type: "required", message: "Permanent resident date is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_green_card_number",
    label: "Green Card / Permanent Resident Card Number",
    type: "text",
    required: true,
    section: "eligibility",
    validationRules: [{ type: "required", message: "Green card number is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_married_to_citizen",
    label: "Are you married to a U.S. citizen?",
    type: "checkbox",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
  {
    id: "n400_citizen_parent",
    label: "Do you have a parent who is a U.S. citizen?",
    type: "checkbox",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
  {
    id: "n400_military_service",
    label: "Have you served in the U.S. Armed Forces?",
    type: "checkbox",
    required: false,
    section: "eligibility",
    rfeRisk: "low",
  },
];

const biographicFields: FormField[] = [
  {
    id: "n400_name_first",
    label: "Current First Name",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "First name is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_name_middle",
    label: "Current Middle Name(s)",
    type: "text",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_name_last",
    label: "Current Last Name",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "Last name is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_date_of_birth",
    label: "Date of Birth",
    type: "date",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "Date of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_gender",
    label: "Gender",
    type: "select",
    required: true,
    section: "biographic",
    options: [
      { value: "M", label: "Male" },
      { value: "F", label: "Female" },
    ],
    rfeRisk: "low",
  },
  {
    id: "n400_height",
    label: "Height",
    type: "text",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_country_of_birth",
    label: "Country of Birth",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "Country of birth is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_current_citizenship",
    label: "Current Citizenship(s)",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "Current citizenship is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_permanent_resident_card_number",
    label: "A-Number (on Green Card)",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "A-Number is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_ssn",
    label: "Social Security Number",
    type: "ssn",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "SSN is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_marital_status",
    label: "Current Marital Status",
    type: "select",
    required: true,
    section: "biographic",
    options: [
      { value: "single", label: "Single (Never Married)" },
      { value: "married", label: "Married" },
      { value: "divorced", label: "Divorced" },
      { value: "widowed", label: "Widowed" },
      { value: "separated", label: "Legally Separated" },
    ],
    rfeRisk: "low",
  },
  {
    id: "n400_current_address",
    label: "Current Street Address",
    type: "address",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "Address is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_current_city",
    label: "City / Town",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "City is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_current_state",
    label: "State",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "State is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_current_zip",
    label: "ZIP Code",
    type: "text",
    required: true,
    section: "biographic",
    validationRules: [{ type: "required", message: "ZIP code is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_phone",
    label: "Telephone Number",
    type: "phone",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_email",
    label: "Email Address",
    type: "text",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_parents_names",
    label: "Father's Name",
    type: "text",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_mother_name",
    label: "Mother's Name",
    type: "text",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_prior_names",
    label: "Have you used any other names?",
    type: "checkbox",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
  {
    id: "n400_prior_names_list",
    label: "Other Names Previously Used",
    type: "textarea",
    required: false,
    section: "biographic",
    rfeRisk: "low",
  },
];

const residenceFields: FormField[] = [
  {
    id: "n400_continuous_residence_years",
    label: "How many years have you lived continuously in the U.S.?",
    type: "text",
    required: true,
    section: "residence",
    placeholder: "Enter number of years",
    validationRules: [{ type: "required", message: "Years of continuous residence is required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_absences_from_us",
    label: "Have you been absent from the U.S. for more than 6 months at any time?",
    type: "checkbox",
    required: false,
    section: "residence",
    rfeRisk: "medium",
  },
  {
    id: "n400_absences_details",
    label: "Describe Your Absences from the U.S.",
    type: "textarea",
    required: false,
    section: "residence",
    helpText: "List dates and reasons for trips outside the U.S.",
    rfeRisk: "medium",
  },
  {
    id: "n400_employment_history",
    label: "Employment History for Last 5 Years",
    type: "textarea",
    required: false,
    section: "residence",
    helpText: "List employers, positions, and dates of employment",
    rfeRisk: "low",
  },
  {
    id: "n400_current_occupation",
    label: "Current Occupation",
    type: "text",
    required: false,
    section: "residence",
    rfeRisk: "low",
  },
  {
    id: "n400_current_employer",
    label: "Current Employer",
    type: "text",
    required: false,
    section: "residence",
    rfeRisk: "low",
  },
  {
    id: "n400_unemployment_periods",
    label: "Have you been unemployed for 6 or more months in the last 5 years?",
    type: "checkbox",
    required: false,
    section: "residence",
    rfeRisk: "medium",
  },
  {
    id: "n400_unemployment_details",
    label: "Describe Periods of Unemployment",
    type: "textarea",
    required: false,
    section: "residence",
    rfeRisk: "medium",
  },
];

const moralCharacterFields: FormField[] = [
  {
    id: "n400_criminal_conviction",
    label: "Have you ever been convicted of a crime?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_criminal_conviction_details",
    label: "Details of Criminal Conviction(s)",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_drug_offense",
    label: "Have you ever been arrested for a drug-related offense?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_drug_offense_details",
    label: "Details of Drug Offense(s)",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_prostitution_charge",
    label: "Have you been charged with prostitution?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_prostitution_details",
    label: "Details of Prostitution Charge(s)",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_money_laundering",
    label: "Have you been involved in money laundering or illegal gambling?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_money_laundering_details",
    label: "Details of Money Laundering or Illegal Gambling",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_immigration_fraud",
    label: "Have you ever misrepresented information to USCIS?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_immigration_fraud_details",
    label: "Details of Misrepresentation",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_persecuted_others",
    label: "Have you ever persecuted others?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_persecuted_details",
    label: "Details of Persecution",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_terrorist_support",
    label: "Have you supported terrorism or terrorist organizations?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_terrorist_support_details",
    label: "Details of Terrorist Support",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_military_unit_crimes",
    label: "Have you committed a crime as part of a military unit?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_military_unit_crimes_details",
    label: "Details of Military Unit Crimes",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_weapons_violation",
    label: "Have you violated any laws regarding weapons?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_weapons_violation_details",
    label: "Details of Weapons Violation(s)",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_tax_evasion",
    label: "Have you ever failed to pay taxes or committed tax evasion?",
    type: "checkbox",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
  {
    id: "n400_tax_evasion_details",
    label: "Details of Tax Issues",
    type: "textarea",
    required: false,
    section: "moral_character",
    rfeRisk: "high",
  },
];

const oathFields: FormField[] = [
  {
    id: "n400_oath_understanding",
    label: "Do you understand the Oath of Allegiance to the United States?",
    type: "checkbox",
    required: true,
    section: "oath",
    validationRules: [{ type: "required", message: "You must confirm understanding of the oath" }],
    rfeRisk: "low",
  },
  {
    id: "n400_willingness_to_take_oath",
    label: "Are you willing to take the Oath of Allegiance?",
    type: "checkbox",
    required: true,
    section: "oath",
    validationRules: [{ type: "required", message: "You must confirm willingness to take the oath" }],
    rfeRisk: "low",
  },
  {
    id: "n400_english_proficiency",
    label: "Can you read, write, and speak basic English?",
    type: "checkbox",
    required: true,
    section: "oath",
    validationRules: [{ type: "required", message: "English proficiency confirmation required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_civics_understanding",
    label: "Do you have basic knowledge of U.S. history and civics?",
    type: "checkbox",
    required: true,
    section: "oath",
    validationRules: [{ type: "required", message: "Civics knowledge confirmation required" }],
    rfeRisk: "low",
  },
  {
    id: "n400_waiver_requested",
    label: "Are you requesting a waiver of the English or civics test?",
    type: "checkbox",
    required: false,
    section: "oath",
    rfeRisk: "low",
  },
  {
    id: "n400_waiver_reason",
    label: "Reason for Requesting Waiver",
    type: "textarea",
    required: false,
    section: "oath",
    helpText: "Explain your reason for requesting a waiver (age, disability, medical condition, etc.)",
    rfeRisk: "low",
  },
];

const declarationFields: FormField[] = [
  {
    id: "n400_declaration_true",
    label: "I declare under penalty of perjury that the foregoing information is true and correct",
    type: "checkbox",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "You must declare the information is true and correct" }],
    rfeRisk: "low",
  },
  {
    id: "n400_signature_date",
    label: "Date of Signature",
    type: "date",
    required: true,
    section: "declaration",
    validationRules: [{ type: "required", message: "Signature date is required" }],
    rfeRisk: "low",
  },
];

export const n400FormDefinition: FormDefinition = {
  id: "n-400",
  formNumber: "N-400",
  title: "Application for Naturalization",
  description:
    "This form is filed to apply for U.S. citizenship through naturalization. You must be a permanent resident for at least 3-5 years (depending on your situation), demonstrate good moral character, and pass English and civics tests to be eligible.",
  effectiveDate: "09/27/2022",
  sections: [
    {
      id: "eligibility",
      title: "Eligibility Information",
      description: "Information about your eligibility for naturalization",
      fields: eligibilityFields,
    },
    {
      id: "biographic",
      title: "Your Biographical Information",
      description: "Personal and identifying information",
      fields: biographicFields,
    },
    {
      id: "residence",
      title: "Residence and Employment History",
      description: "Your residence and employment history in the United States",
      fields: residenceFields,
    },
    {
      id: "moral_character",
      title: "Moral Character Questions",
      description: "Criminal history and moral character questions",
      fields: moralCharacterFields,
    },
    {
      id: "oath",
      title: "Oath and Test Information",
      description: "Information about the Oath of Allegiance and required tests",
      fields: oathFields,
    },
    {
      id: "declaration",
      title: "Declaration and Signature",
      description: "Certification and signature",
      fields: declarationFields,
    },
  ],
  fieldCount: eligibilityFields.length + biographicFields.length + residenceFields.length + moralCharacterFields.length + oathFields.length + declarationFields.length,
  estimatedTime: 75,
};

export default n400FormDefinition;
